### ISSUE TITLE
lint broken after upgrade to eslint-config-airbnb@11.1.0

### ISSUE THREAD

**Issue by Fandekasp** [airbnb/javascript#1064]
Error
```
$ npm run lint
Referenced from: /path/to/project/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
Referenced from: /path/to/project/.eslintrc.yml
        Configuration for rule "max-len" is invalid:
        Value "data["2"].ignoreStrings" has additional properties.
        Value "data["2"].ignoreTemplateLiterals" has additional properties.
```

Package versions
```
$ npm ls | grep eslint  
├─┬ babel-eslint@6.1.2
├─┬ UNMET PEER DEPENDENCY eslint@3.4.0
├─┬ eslint-config-airbnb@11.1.0 invalid
│ ├── UNMET PEER DEPENDENCY eslint@^3.5.0
│ └── eslint-config-airbnb-base@7.1.0
├── eslint-plugin-flowtype@2.16.0
├─┬ eslint-plugin-import@1.14.0
│ ├─┬ eslint-import-resolver-node@0.2.3
├─┬ eslint-plugin-jsx-a11y@2.2.1
├── eslint-plugin-react@6.2.0
```

.eslintrc
```
extends: airbnb

parser: babel-eslint

parserOptions:
  ecmaFeatures:
  jsx: true

plugins:
  - react
  - jsx-a11y
  - import
  - flowtype

rules:
  # Enable
  #  flowtype/define-flow-type: 1
  #  flowtype/use-flow-type: 1

  # Disable
  react/jsx-filename-extension: 0  # unsupported by react-native
  react/require-extension: 0  # deprecated. use eslint-plugin-import instead
```

My .eslintrc file doesn't reference max-len, but the error is triggered. It looks like a bug in `eslint-config-airbnb-base/index.js`. Same issue occurs for 11.0.0 and 11.1.0
