### ISSUE TITLE
Lint throw an "error"

### ISSUE THREAD

**Issue by guidiego** [airbnb/javascript#1209]
Hey guys, when I try to exec a simple lint I receive that message:

```
 Configuration for rule "jsx-a11y/anchor-has-content" is invalid:
	Value "" is the wrong type.
```

My `.eslintrc.yml` :

```yaml
extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import

```

Edit: I was look at file and saw the modifications like `['']` to `{components: ['']}` done, but the module that I installed using `yarn` hasn't this modifications :/
