### ISSUE TITLE
Mocha arrow-function and unnamed function errors.

### ISSUE THREAD

**Issue by FieryCod** [airbnb/javascript#1379]
Hello community I am receiving errors whenever I am using using `describe(function(){})` in my code.
How can I get rid of these errors?
Here is my .eslintrc.yml.

```
extends: airbnb-base
plugins:
  - standard
  - promise
env:
    node: true
    mocha: true
rules:
    indent: ["error", 2]
    semi: ["error", "always", {omitLastInOneLineBlock: true}]
    no-eval: ["error"]
    no-trailing-spaces: ["error"]
    one-var-declaration-per-line: ["error", "initializations"]
    no-irregular-whitespace: ["error"]
    no-var: ["error"]
    no-empty: ["error"]
    linebreak-style: ["error", "unix"]
    eol-last: ["error", "always"]
    no-console: ["warn", {"allow": ["warn", "error", "info"]}]
    no-use-before-define: ["error", { "functions": false }]
    no-unused-vars: ["error", {"argsIgnorePattern":"^next"}]
```
Tried to add mocha-plugin like so:
```
plugins:
- mocha
rules:
mocha/no-arrow-function: "error"
```
but it still gives me errors.
