### ISSUE TITLE
Incorrect indentation undetected for JS code within JSX

### ISSUE THREAD

**Issue by astorije** [airbnb/javascript#1711]
Consider an ESLint configuration file that just says:

```yaml
extends: airbnb
```

and the following JS code:

```js
import React from 'react';
import Foobar from './Foobar';

function foo() {
  return 'Foo!';
}

export default function () {
  return (
    <Foobar
      render={() => {
               const myFoo = foo();

        return <span>{myFoo}</span>;
      }}
    />
  );
}
```

This passes the linter, i.e. the incorrectly indented `const myFoo` line does not get flagged. I could repro this with v16.1.0 and `master`.
This same incorrect indentation in the `foo` function definition is however correctly flagged.

I initially thought this was an issue in [`eslint-plugin-react`](https://github.com/yannickcr/eslint-plugin-react), so I made this minimalist config:

```yaml
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - react

rules:
  indent:
    - error
    - 2
  react/jsx-indent:
    - error
    - 2
```

With this, the indentation is correctly flagged:

```
12:1  error  Expected indentation of 8 spaces but found 12  indent
```
